### ISSUE TITLE
Merge entitlements branch?

### ISSUE THREAD

**Issue by mstone** [thefloweringash/sigtool#4]
Dear @thefloweringash,

Thanks for writing `sigtool` and for publishing your WIP `entitlements` branch at db1f32bb7de43cee8801880fbb88be8764fe75bb. Using this commit and its predecessors, I am now able to produce working `qemu-system-aarch64` aarch64-darwin binaries with the required `Hypervisor.framework` entitlement via a (unfortunately still somewhat hacky) nix flake: mstone/qemu-m1@9f58927d01f1b29dfab152be715d8bcc1feebff2, which I am thrilled by.

Next, regarding the `entitlements` branch itself and parallel to @isuruf's question in #2: what in your view remains to be done before the `entitlements` branch can reasonably be merged / declared generally ready for use?

Thanks + regards!

**Comment by thefloweringash** [comment]
Sorry I haven’t found a lot of time to work on this lately .The motivation for the `entitlements` branch is to fix the signing for the qemu build in nixpkgs. It adds support for inserting plist-style entitlements (but not BER-formatted entitlements),  and also adds a new `codesign` entry point that supports an `--entitlements` flag. To finish the branch I want to test that the qemu build works as expected. I was also hoping to add some automated test cases, but that can wait.

I didn’t know if BER formatted entitlements were required, but since it’s working in your flake then they must not be. 🎉 

I did notice in your flake that you’re using the low level `sigtool` entry point to sign the result of the unsigned build. It should work if you put `sigtool` into the `nativeBuildInputs` to put the `codesign`-compatible entry point on the path, and re-enable signing. If this works, then I’ll tidy up the branch and merge it.

**Comment by mstone** [comment]
Quick update: I’ve performed the test you requested but unfortunately, it seems a couple tweaks are needed to get things working with qemu’s integrated `entitlements.sh` script.

As a result, I’ll see if I can scrape a PR together for you once I’ve got things working…
